### ISSUE TITLE
Angular 13 unsupported

### ISSUE THREAD

**Issue by eddiepineapples** [pierreavn/angular-tabler-icons#14]
Any chance of supporting Angular 13?

**Comment by pierreavn** [comment]
Hi,

Thank you for reporting this issue.
I'm working on it and keep you in touch when Angular 13 support is ready.

Regards

**Comment by pierreavn** [comment]
I've just deployed a new package version with Angular 13 support, can you give it a try?
```bash
npm install angular-tabler-icons@angular-tabler-icons@1.53.1
```
or
```bash
yarn add angular-tabler-icons@1.53.1
```

**Comment by eddiepineapples** [comment]
Thanks, this worked for me in 13.1.2 🎉 

Some notes while implementing:

- The styles in `angular-tabler-icons.metadata.json` have a higher specificity than styles I apply via a class.  I have to use `!important` to get my styles to work.  In my case I'm setting the width and height to 1em.
- It would be cool if we had `ti` as a selector option for convenience.

**Comment by pierreavn** [comment]
Perfect!

About your notes:
- Indeed I'm afraid I can do nothing to fix that, because styles are directly applied on `<i-tabler>` component. You should use `!important` to override default style.
- Yes, it would be cool! Unfortunately, we need to not provide too short components names to avoid conflicts between packages and components. But you can wrap it in your own component!

```ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'ti',
  template: `<i-tabler [name]="name"></i-tabler>`
})
export class TablerIconComponent {
  @Input() name!: string;
}
```

I you see other things, do not hesitate to contribute to the package with Pull Requests :)
